const fallback=[{"id":"cashflow-intelligence","title":"CashFlow Intelligence","category":"Dados & BI","status":"MVP concluído","year":"2026","summary":"Inteligência financeira para acompanhar realizado, previsto, atrasos e disponibilidade de caixa.","technologies":["Power BI","Power Query","DAX","Python"],"metrics":{"movimentos": 1600, "entradas": 7323077.61, "saidas": 7864273.98, "saldo": -541196.37, "valor_vencido": 98220.44, "taxa_atraso": 11.4, "periodo": "jan/2025–ago/2026"}}];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',notation:'compact',maximumFractionDigits:1}).format(v);let projects=fallback;
async function init(){try{const r=await fetch('data/projects.json');if(r.ok)projects=await r.json()}catch(e){}render(projects);document.querySelector('#project-count').textContent=String(projects.length).padStart(2,'0')}
function render(items){const g=document.querySelector('#project-grid');g.innerHTML=items.map(p=>`<article class="project"><div class="project-visual" aria-label="Prévia visual do dashboard"><div class="mini-kpi"><small>ENTRADAS</small><b>${money(p.metrics.entradas)}</b></div><div class="mini-kpi"><small>SAÍDAS</small><b>${money(p.metrics.saidas)}</b></div><div class="mini-kpi"><small>SALDO</small><b>${money(p.metrics.saldo)}</b></div><div class="mini-chart" aria-hidden="true">${[44,62,53,76,67,88,79,96,84,100].map((h,i)=>`<i style="height:${h}%;--i:${i}"></i>`).join('')}</div></div><div class="project-copy"><div class="project-top"><span class="eyebrow">${p.category} • ${p.year}</span><span class="status">● ${p.status}</span></div><h3>${p.title}</h3><p>${p.summary}</p><div class="tags">${p.technologies.map(t=>`<span class="tag">${t}</span>`).join('')}</div><button class="open-project" data-id="${p.id}">Ver case completo →</button></div></article>`).join('');document.querySelectorAll('.open-project').forEach(b=>b.onclick=()=>openProject(b.dataset.id))}
function openProject(id){const p=projects.find(x=>x.id===id),m=p.metrics;document.querySelector('#dialog-content').innerHTML=`<p class="eyebrow">CASE DE PORTFÓLIO</p><h2>${p.title}</h2><p class="lede">${p.summary}</p><div class="detail-grid"><div><small>Movimentos</small><b>${m.movimentos.toLocaleString('pt-BR')}</b></div><div><small>Saldo realizado</small><b>${money(m.saldo)}</b></div><div><small>Taxa de atraso</small><b>${m.taxa_atraso}%</b></div></div><h3>Desafio</h3><p>Consolidar lançamentos dispersos e criar uma visão confiável do caixa realizado, previsto e vencido.</p><h3>Solução</h3><ul class="detail-list"><li>Base sintética documentada e pronta para Power BI</li><li>Modelo dimensional com regras de negócio explícitas</li><li>KPIs executivos e visão operacional</li><li>Arquitetura reproduzível e segura para publicação</li></ul><div class="actions"><a class="primary" href="data/fluxo_caixa.csv" download>Baixar dados</a><a class="secondary" href="projects/cashflow-intelligence/README.md">Documentação técnica</a></div>`;document.querySelector('#project-dialog').showModal()}
document.querySelector('.close').onclick=()=>document.querySelector('#project-dialog').close();document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter==='all'?projects:projects.filter(p=>p.category===b.dataset.filter))});init();

// Theme: system preference on first visit, persisted after user choice.
const root=document.documentElement,themeButton=document.querySelector('#theme-toggle');
const savedTheme=localStorage.getItem('portfolio-theme');
const initialTheme=savedTheme||((matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light');
function applyTheme(theme){root.dataset.theme=theme;const dark=theme==='dark';themeButton.setAttribute('aria-pressed',String(dark));themeButton.setAttribute('aria-label',dark?'Ativar tema claro':'Ativar tema escuro')}
applyTheme(initialTheme);themeButton.addEventListener('click',()=>{const next=root.dataset.theme==='dark'?'light':'dark';applyTheme(next);localStorage.setItem('portfolio-theme',next)});

// Subtle particle field. Pointer repels; holding/clicking attracts briefly.
(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const c=document.querySelector('#starfield'),x=c.getContext('2d');let w,h,dpr,particles=[],pointer={x:-9999,y:-9999,down:false};
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';x.setTransform(dpr,0,0,dpr,0,0);const count=Math.min(120,Math.max(48,Math.floor(w*h/13500)));particles=Array.from({length:count},(_,i)=>({x:(i*89.3)%w,y:(i*53.7)%h,vx:0,vy:0,r:.7+(i%4)*.32}))}
function move(e){pointer.x=e.clientX;pointer.y=e.clientY}addEventListener('pointermove',move,{passive:true});addEventListener('pointerdown',e=>{move(e);pointer.down=true});addEventListener('pointerup',()=>pointer.down=false);addEventListener('pointerleave',()=>{pointer.x=-9999;pointer.y=-9999;pointer.down=false});addEventListener('resize',resize,{passive:true});
function frame(){x.clearRect(0,0,w,h);const color=getComputedStyle(root).getPropertyValue('--star').trim()||'36,116,210';for(const p of particles){let dx=p.x-pointer.x,dy=p.y-pointer.y,dist=Math.hypot(dx,dy)||1;if(dist<150){const force=(1-dist/150)*(pointer.down?-.045:.075);p.vx+=dx/dist*force;p.vy+=dy/dist*force}p.vx*=.965;p.vy*=.965;p.x+=p.vx+.025;p.y+=p.vy;if(p.x<-8)p.x=w+8;if(p.x>w+8)p.x=-8;if(p.y<-8)p.y=h+8;if(p.y>h+8)p.y=-8;x.beginPath();x.arc(p.x,p.y,p.r,0,Math.PI*2);x.fillStyle=`rgba(${color},${.16+p.r*.08})`;x.fill()}requestAnimationFrame(frame)}resize();frame()})();
