const BASE=document.body.dataset.base||'.';
const PAGE=document.body.dataset.page||'';
const LANG=localStorage.getItem('portfolio-lang')||((navigator.language||'pt').toLowerCase().startsWith('en')?'en-US':'pt-BR');
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const tx=(pt,en)=>LANG==='en-US'?en:pt;
function chrome(){
 const nav=[['inicio','Início','Home','index.html'],['sobre','Sobre','About','sobre/index.html'],['carreira','Carreira','Career','carreira/index.html'],['skills','Competências','Skills','skills/index.html'],['projetos','Projetos','Projects','projetos/index.html'],['labs','Labs','Labs','labs/index.html'],['contato','Contato','Contact','contato/index.html']];
 const icon=(name)=>({github:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 .8a11.2 11.2 0 0 0-3.54 21.83c.56.1.77-.24.77-.54v-2.16c-3.13.68-3.79-1.33-3.79-1.33-.51-1.3-1.25-1.65-1.25-1.65-1.02-.7.08-.68.08-.68 1.13.08 1.72 1.16 1.72 1.16 1 1.72 2.63 1.22 3.27.93.1-.73.39-1.22.71-1.5-2.5-.28-5.13-1.25-5.13-5.56 0-1.23.44-2.23 1.16-3.02-.12-.28-.5-1.43.11-2.98 0 0 .95-.3 3.08 1.15A10.7 10.7 0 0 1 12 6.27c.95 0 1.9.13 2.8.38 2.14-1.45 3.08-1.15 3.08-1.15.62 1.55.23 2.7.12 2.98.72.79 1.16 1.79 1.16 3.02 0 4.32-2.64 5.27-5.15 5.55.4.35.76 1.03.76 2.08v2.96c0 .3.2.65.78.54A11.2 11.2 0 0 0 12 .8Z"/></svg>',linkedin:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5.3 7.8H1.1V21h4.2V7.8ZM3.2 1.2A2.4 2.4 0 1 0 3.2 6a2.4 2.4 0 0 0 0-4.8ZM21 13.4c0-4-2.1-5.9-5-5.9-2.3 0-3.4 1.3-4 2.2V7.8H7.8V21H12v-6.5c0-1.7.33-3.4 2.5-3.4 2.2 0 2.2 2 2.2 3.5V21H21v-7.6Z"/></svg>',mail:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 4h18a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Zm9 8 8-5V6l-8 5-8-5v1l8 5Z"/></svg>'})[name];
 q('#site-header').innerHTML=`<nav class="navbar"><a class="brand brand-wide" href="${BASE}/index.html" aria-label="Kaíque Passaros — início"><img src="${BASE}/assets/brand/brand-mark.png" alt=""><span><strong>Kaíque Passaros</strong><small>${tx('Dados & BI','Data & BI')}</small></span></a><button class="menu-toggle" aria-label="${tx('Abrir menu','Open menu')}" aria-expanded="false"><span></span><span></span></button><div class="nav-links">${nav.map(([id,pt,en,path])=>`<a class="${PAGE===id?'active':''}" href="${BASE}/${path}"><span>${tx(pt,en)}</span></a>`).join('')}<div class="nav-actions"><div class="language-picker"><button class="lang-trigger" aria-haspopup="listbox" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.4 2.5 3.6 5.5 3.6 9s-1.2 6.5-3.6 9c-2.4-2.5-3.6-5.5-3.6-9S9.6 5.5 12 3Z"/></svg><span class="control-label">${LANG==='en-US'?'EN-US':'PT-BR'}</span><svg class="chevron" viewBox="0 0 24 24" aria-hidden="true"><path d="m7 10 5 5 5-5"/></svg></button><div class="lang-menu" role="listbox" hidden><button role="option" data-lang="pt-BR" aria-selected="${LANG==='pt-BR'}">${LANG==='pt-BR'?'✓ ':''}Português — Brasil</button><button role="option" data-lang="en-US" aria-selected="${LANG==='en-US'}">${LANG==='en-US'?'✓ ':''}English — US</button></div></div><button class="theme-toggle" aria-label="${tx('Alternar tema','Toggle theme')}"><svg class="sun" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg><svg class="moon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15.3A8.5 8.5 0 0 1 8.7 4a8.5 8.5 0 1 0 11.3 11.3Z"/></svg></button></div></div></nav>`;
 q('#site-footer').innerHTML=`<div class="footer-shell"><a class="footer-brand" href="${BASE}/index.html"><img src="${BASE}/assets/brand/brand-mark.png" alt=""><span><strong>Kaíque Passaros</strong><small>${tx('Dados • BI • Transformação Digital','Data • BI • Digital Transformation')}</small></span></a><nav class="footer-socials" aria-label="${tx('Links profissionais','Professional links')}"><a href="mailto:kaiquepassarosva@gmail.com" aria-label="Email">${icon('mail')}<span>Email</span></a><a href="https://github.com/kpassaros" target="_blank" rel="noopener" aria-label="GitHub">${icon('github')}<span>GitHub</span></a><a href="https://www.linkedin.com/in/kaiquepassaros/" target="_blank" rel="noopener" aria-label="LinkedIn">${icon('linkedin')}<span>LinkedIn</span></a></nav><div class="footer-status"><i></i><span>${tx('Portfólio publicado no GitHub Pages','Portfolio on GitHub Pages')}</span></div></div>`;
 const mt=q('.menu-toggle'),links=q('.nav-links');mt.onclick=()=>{const open=links.classList.toggle('open');mt.setAttribute('aria-expanded',open)};
 const trigger=q('.lang-trigger'),menu=q('.lang-menu');trigger.onclick=e=>{e.stopPropagation();menu.hidden=!menu.hidden;trigger.setAttribute('aria-expanded',String(!menu.hidden))};
 qa('[data-lang]').forEach(b=>b.onclick=()=>{localStorage.setItem('portfolio-lang',b.dataset.lang);location.reload()});
 addEventListener('click',()=>{if(menu&&!menu.hidden){menu.hidden=true;trigger.setAttribute('aria-expanded','false')}});addEventListener('keydown',e=>{if(e.key==='Escape'&&menu){menu.hidden=true;trigger.setAttribute('aria-expanded','false')}});const header=q('#site-header'),syncHeader=()=>header?.classList.toggle('is-scrolled',scrollY>6);syncHeader();addEventListener('scroll',syncHeader,{passive:true})
}
function theme(){const root=document.documentElement,saved=localStorage.getItem('portfolio-theme')||root.dataset.theme||'dark',button=q('.theme-toggle'),meta=q('meta[name="theme-color"]');const sync=()=>{const dark=root.dataset.theme==='dark';if(meta)meta.content=dark?'#111514':'#e3e6e7';if(button){button.setAttribute('aria-label',tx(dark?'Ativar tema claro':'Ativar tema escuro',dark?'Switch to light theme':'Switch to dark theme'));button.title=button.getAttribute('aria-label')}};root.dataset.theme=saved;sync();if(button)button.onclick=()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('portfolio-theme',root.dataset.theme);sync()}}
function loader(){
 const el=q('#page-loader');if(!el)return;if(PAGE!=='inicio'){el.remove();return}
 const canvas=q('#loader-network',el),ctx=canvas?.getContext('2d'),media=q('#hero-character'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const started=performance.now(),minTime=reduced?450:2450,maxTime=4400;let resourceReady=!media||media.readyState>=3,done=false,raf=0,w=0,h=0,dpr=1,nodes=[],edges=[],pulses=[],cx=0,cy=0;
 const clamp=v=>Math.max(0,Math.min(1,v)),ease=v=>1-Math.pow(1-v,3);
 const resize=()=>{if(!canvas||!ctx)return;dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;cx=w/2;cy=h/2;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const total=w<600?38:72,maxR=Math.hypot(w,h)*.53;nodes=Array.from({length:total},(_,i)=>{const ring=1+Math.floor(i/9),angle=i*2.399+Math.sin(i)*.18,radius=Math.min(maxR,(ring/(Math.ceil(total/9)+.15))*maxR)*(0.78+((i*37)%21)/100);return{tx:cx+Math.cos(angle)*radius,ty:cy+Math.sin(angle)*radius,born:i/(total*.9),size:2.1+(i%5)*.45,x:cx,y:cy}});edges=[];nodes.forEach((n,i)=>{const prev=nodes.slice(0,i).map((o,j)=>({j,d:Math.hypot(n.tx-o.tx,n.ty-o.ty)})).sort((a,b)=>a.d-b.d).slice(0,i%4===0?3:2);prev.forEach(v=>{if(v.d<Math.max(180,Math.min(w,h)*.34))edges.push([i,v.j])})});pulses=[]};
 const draw=now=>{if(done||!ctx)return;const elapsed=now-started,progress=clamp(elapsed/minTime);ctx.clearRect(0,0,w,h);nodes.forEach(n=>{const local=ease(clamp((progress-n.born)/.24));n.x=cx+(n.tx-cx)*local;n.y=cy+(n.ty-cy)*local});edges.forEach(([ai,bi],idx)=>{const a=nodes[ai],b=nodes[bi],born=Math.max(a.born,b.born);if(progress<born)return;const reveal=ease(clamp((progress-born)/.16));ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(a.x+(b.x-a.x)*reveal,a.y+(b.y-a.y)*reveal);ctx.strokeStyle=`rgba(73,157,242,${.08+reveal*.3})`;ctx.lineWidth=progress>.82?1.15:1.35;ctx.stroke();if(progress>.28&&reveal>.8){const t=(elapsed*.00042+idx*.173)%1,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;ctx.beginPath();ctx.arc(x,y,idx%6===0?3.7:2.3,0,Math.PI*2);ctx.fillStyle='rgba(111,190,255,.96)';ctx.shadowColor='rgba(66,158,248,.95)';ctx.shadowBlur=14;ctx.fill();ctx.shadowBlur=0}});nodes.forEach((n,i)=>{if(progress<n.born)return;const local=clamp((progress-n.born)/.16),pulse=1+Math.sin(elapsed*.004+i)*.2;ctx.beginPath();ctx.arc(n.x,n.y,n.size*local*pulse,0,Math.PI*2);ctx.fillStyle='rgba(92,177,255,.88)';ctx.shadowColor='rgba(55,145,235,.9)';ctx.shadowBlur=9;ctx.fill();ctx.shadowBlur=0});raf=requestAnimationFrame(draw)};
 const handoff=()=>{if(done||performance.now()-started<minTime||!resourceReady)return;done=true;cancelAnimationFrame(raf);el.classList.add('handoff');document.body.classList.add('content-ready');setTimeout(()=>{el.classList.add('complete');document.body.classList.remove('loader-active','home-loading')},720);setTimeout(()=>el.remove(),1550)};
 if(media&&!resourceReady)media.addEventListener('canplay',()=>{resourceReady=true;handoff()},{once:true});
 if(!reduced){resize();addEventListener('resize',resize,{passive:true});raf=requestAnimationFrame(draw)}
 setTimeout(handoff,minTime);setTimeout(()=>{resourceReady=true;handoff()},maxTime)
}
function neural(){
 const c=q('#starfield');if(!c)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)return;const ctx=c.getContext('2d');let w,h,dpr,nodes=[],edges=[],pulses=[],pointer={x:-999,y:-999},cluster=null,lastBurst=0,nextBurst=650;
 const rand=(a,b)=>a+Math.random()*(b-a);
 function rebuild(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const total=Math.min(118,Math.max(62,Math.floor(w*h/14500)));nodes=Array.from({length:total},(_,i)=>({bx:rand(0,w),by:rand(0,h),x:0,y:0,r:rand(2.2,4.1),phase:rand(0,7)}));nodes.forEach(n=>{n.x=n.bx;n.y=n.by});edges=[];nodes.forEach((n,i)=>{const near=nodes.map((o,j)=>({o,j,d:Math.hypot(o.bx-n.bx,o.by-n.by)})).filter(v=>v.j!==i).sort((a,b)=>a.d-b.d).slice(0,3);near.forEach(v=>{const a=Math.min(i,v.j),b=Math.max(i,v.j);if(v.d<235&&!edges.some(e=>e.ai===a&&e.bi===b))edges.push({ai:a,bi:b,a:nodes[a],b:nodes[b]})})});window.__networkStats={nodes:nodes.length,edges:edges.length,pulses:0}}
 function launch(count=5,origin=null,strong=false){let pool=edges;if(origin)pool=edges.filter(e=>Math.min(Math.hypot(e.a.x-origin.x,e.a.y-origin.y),Math.hypot(e.b.x-origin.x,e.b.y-origin.y))<300);if(!pool.length)pool=edges;for(let i=0;i<count;i++){const edge=pool[Math.floor(Math.random()*pool.length)];const reverse=Math.random()>.5;pulses.push({a:reverse?edge.b:edge.a,b:reverse?edge.a:edge.b,t:rand(-.12,.12),speed:rand(strong?.018:.009,strong?.027:.015),strong})}window.__networkStats.pulses=pulses.length}
 addEventListener('resize',rebuild);addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY},{passive:true});addEventListener('pointerleave',()=>{pointer.x=pointer.y=-999});addEventListener('pointerdown',e=>{cluster={x:e.clientX,y:e.clientY,start:performance.now(),life:1900};launch(18,{x:e.clientX,y:e.clientY},true)});
 function draw(now){ctx.clearRect(0,0,w,h);const rgb=getComputedStyle(document.documentElement).getPropertyValue('--star').trim()||'36,116,210';let phase=0;if(cluster){phase=Math.min(1,(now-cluster.start)/cluster.life);if(phase>=1)cluster=null}
  nodes.forEach(n=>{let tx=n.bx+Math.sin(now*.00018+n.phase)*5,ty=n.by+Math.cos(now*.00015+n.phase)*5;if(cluster){const d=Math.hypot(n.bx-cluster.x,n.by-cluster.y);if(d<270){const pull=Math.sin(phase*Math.PI)*.66,ang=Math.atan2(n.by-cluster.y,n.bx-cluster.x),radius=42+d*.24;tx=tx*(1-pull)+(cluster.x+Math.cos(ang)*radius)*pull;ty=ty*(1-pull)+(cluster.y+Math.sin(ang)*radius)*pull}}n.x+=(tx-n.x)*.1;n.y+=(ty-n.y)*.1});
  edges.forEach(e=>{const mx=(e.a.x+e.b.x)/2,my=(e.a.y+e.b.y)/2,near=Math.hypot(mx-pointer.x,my-pointer.y)<210;ctx.beginPath();ctx.moveTo(e.a.x,e.a.y);ctx.lineTo(e.b.x,e.b.y);ctx.lineWidth=near?1.75:1.15;ctx.strokeStyle=`rgba(${rgb},${near?.34:.17})`;ctx.stroke()});
  nodes.forEach(n=>{const near=Math.hypot(n.x-pointer.x,n.y-pointer.y)<190;ctx.beginPath();ctx.arc(n.x,n.y,n.r+(near?.7:0),0,Math.PI*2);ctx.fillStyle=`rgba(${rgb},${near?.92:.62})`;ctx.shadowColor=`rgba(${rgb},.72)`;ctx.shadowBlur=near?12:5;ctx.fill();ctx.shadowBlur=0});
  if(now-lastBurst>nextBurst){launch(Math.floor(rand(4,8)));lastBurst=now;nextBurst=rand(620,1150)}
  pulses=pulses.filter(o=>{const mx=(o.a.x+o.b.x)/2,my=(o.a.y+o.b.y)/2,boost=Math.hypot(mx-pointer.x,my-pointer.y)<220?2.6:1;o.t+=o.speed*boost;const t=Math.max(0,o.t),tail=Math.max(0,t-(o.strong?.2:.12)),x1=o.a.x+(o.b.x-o.a.x)*tail,y1=o.a.y+(o.b.y-o.a.y)*tail,x2=o.a.x+(o.b.x-o.a.x)*t,y2=o.a.y+(o.b.y-o.a.y)*t;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.lineWidth=o.strong?3.5:2.4;ctx.strokeStyle=`rgba(${rgb},${o.strong?.96:.82})`;ctx.shadowColor=`rgba(${rgb},1)`;ctx.shadowBlur=o.strong?18:13;ctx.stroke();ctx.beginPath();ctx.arc(x2,y2,o.strong?4.6:3.4,0,Math.PI*2);ctx.fillStyle=`rgba(${rgb},1)`;ctx.fill();ctx.shadowBlur=0;return o.t<1.02});window.__networkStats.pulses=pulses.length;requestAnimationFrame(draw)}
 rebuild();launch(7);requestAnimationFrame(draw)
}
async function projects(){const r=await fetch(`${BASE}/data/projects.json`);if(!r.ok)throw Error('catalog');let data=await r.json();return data.map(p=>LANG==='en-US'&&p.i18n?.['en-US']?{...p,...p.i18n['en-US']}:p)}
function slug(v=''){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-')}
function projectCard(p){const bars=[36,63,48,78,58,91,72,98,82,88];return `<article class="project-card" data-id="${p.id}" data-category="${p.category}"><div class="project-cover"><img src="${BASE}/content/projects/${p.id}/${p.cover}" alt="${p.title}"><div class="mini-chart" aria-hidden="true">${bars.map((v,i)=>`<i style="--h:${v}%;--i:${i}"></i>`).join('')}</div>${p.new?`<span class="new-badge">${tx('NOVO','NEW')}</span>`:''}</div><div class="project-summary"><div class="project-meta"><span>${p.category} • ${p.year}</span><span class="status-badge status-${slug(p.status)}">${p.status}</span></div><h2>${p.title}</h2><p>${p.summary}</p><div class="tags">${p.technologies.slice(0,5).map(t=>`<span>${t}</span>`).join('')}</div><div class="card-actions"><button class="project-open" data-open-project="${p.id}">${tx('Ver detalhes','View details')}</button><a class="project-link" href="${BASE}/projeto/index.html?id=${p.id}">${tx('Ver case','View case')} <span>→</span></a></div></div></article>`}
function ensureModal(){if(q('#project-modal'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="project-modal" class="project-modal"><button class="modal-close" aria-label="${tx('Fechar','Close')}">×</button><div id="modal-content"></div></dialog>`);const d=q('#project-modal');q('.modal-close',d).onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close()};d.addEventListener('close',()=>history.replaceState(null,'',location.pathname+location.search))}
function modalProject(p){ensureModal();const d=q('#project-modal'),el=q('#modal-content');el.innerHTML=`<p class="eyebrow">${p.projectType||p.category}</p><h1>${p.title}</h1><p class="lede">${p.summary}</p><div class="data-disclosure"><b>${p.disclosure?.label||tx('Dados fictícios','Fictitious data')}</b><span>${p.disclosure?.detail||p.dataNature||''}</span></div><div class="modal-grid"><section><small>${tx('PROBLEMA','PROBLEM')}</small><p>${p.problem}</p></section><section><small>${tx('MEU PAPEL','MY ROLE')}</small><p>${p.role}</p></section><section><small>${tx('SOLUÇÃO','SOLUTION')}</small><p>${p.solution}</p></section><section><small>${tx('RESULTADOS','RESULTS')}</small><ul>${p.results.map(r=>`<li>${r}</li>`).join('')}</ul></section></div>${p.stackGroups?.length?`<h3>${tx('Stack do projeto','Project stack')}</h3><div class="stack-groups">${p.stackGroups.map(g=>`<div class="stack-group"><small>${g.label}</small><div class="tags">${g.items.map(i=>`<span>${i}</span>`).join('')}</div></div>`).join('')}</div>`:''}<div class="actions"><a class="primary" href="${BASE}/projeto/index.html?id=${p.id}">${tx('Abrir case completo','Open full case')}</a></div>`;d.showModal();history.replaceState(null,'',`#${p.id}`)}
async function bindCards(data){qa('[data-open-project]').forEach(b=>b.onclick=()=>modalProject(data.find(p=>p.id===b.dataset.openProject)))}
async function featured(){const el=q('#featured-projects');if(!el)return;const data=await projects();const show=data.filter(p=>p.featured).slice(0,3);el.innerHTML=show.map(projectCard).join('');const c=q('#project-count'),pc=q('#public-project-count');if(c)c.textContent=String(data.length).padStart(2,'0');if(pc)pc.textContent=String(data.length).padStart(2,'0');bindCards(data)}
async function catalog(){const el=q('#project-catalog');if(!el)return;const all=await projects(),isLabs=PAGE==='labs',data=isLabs?all.filter(p=>p.category==='Labs'):all,filters=q('#project-filters'),search=q('#project-search');let active='Todos';const facet=p=>isLabs?(p.projectType||p.status):p.category;const cats=['Todos',...new Set(data.map(facet))];filters.innerHTML=cats.map((c,i)=>`<button class="${i?'':'active'}" data-filter="${c}">${LANG==='en-US'&&c==='Todos'?'All':c}</button>`).join('');function draw(){const term=(search.value||'').toLowerCase(),rows=data.filter(p=>(active==='Todos'||facet(p)===active)&&`${p.title} ${p.summary} ${p.technologies.join(' ')}`.toLowerCase().includes(term));el.innerHTML=rows.map(projectCard).join('');q('#project-empty').hidden=!!rows.length;bindCards(data)}filters.onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;active=b.dataset.filter;qa('button',filters).forEach(x=>x.classList.toggle('active',x===b));draw()};search.oninput=draw;draw();if(location.hash)requestAnimationFrame(()=>{const item=data.find(x=>`#${x.id}`===location.hash);if(item)modalProject(item)})}
async function detail(){const el=q('#project-detail');if(!el)return;const id=new URLSearchParams(location.search).get('id'),data=await projects(),p=data.find(x=>x.id===id);if(!p){el.innerHTML='<p>Projeto não encontrado.</p>';return}const demo=p.demo?.mode==='github-html'?`<section class="demo-section"><div class="section-head"><div><p class="eyebrow">${tx('DEMONSTRAÇÃO','DEMO')}</p><h2>${tx('Explore a solução.','Explore the solution.')}</h2></div></div><div class="demo-frame"><iframe src="${BASE}/${p.demo.embedPath}" title="${p.title}" loading="lazy"></iframe></div></section>`:'';el.innerHTML=`<article class="project-case"><a class="back" href="${BASE}/projetos/index.html">← ${tx('Voltar aos projetos','Back to projects')}</a><header><p class="eyebrow">${p.projectType||p.category} • ${p.year}</p><h1>${p.title}</h1><p class="lede">${p.summary}</p><div class="data-disclosure"><b>${p.disclosure?.label||''}</b><span>${p.disclosure?.detail||p.dataNature||''}</span></div><div class="tags">${p.technologies.map(t=>`<span>${t}</span>`).join('')}</div></header><img class="case-cover" src="${BASE}/content/projects/${p.id}/${p.cover}" alt=""><div class="case-grid"><section><small>${tx('PROBLEMA','PROBLEM')}</small><p>${p.problem}</p></section><section><small>${tx('MEU PAPEL','MY ROLE')}</small><p>${p.role}</p></section><section><small>${tx('SOLUÇÃO','SOLUTION')}</small><p>${p.solution}</p></section><section><small>${tx('RESULTADOS','RESULTS')}</small><ul>${p.results.map(r=>`<li>${r}</li>`).join('')}</ul></section></div>${p.stackGroups?.length?`<section><h2>${tx('Stack do projeto','Project stack')}</h2><div class="stack-groups">${p.stackGroups.map(g=>`<div class="stack-group"><small>${g.label}</small><div class="tags">${g.items.map(i=>`<span>${i}</span>`).join('')}</div></div>`).join('')}</div></section>`:''}${demo}</article>`}
async function career(){const el=q('#career-timeline');if(!el)return;let items=await fetch(`${BASE}/data/experience.json`).then(r=>r.json());items=items.map(x=>LANG==='en-US'&&x.en?{...x,...x.en}:x);el.innerHTML=items.map((x,i)=>`<article class="career-entry side-${x.side||(i%2?'left':'right')}" style="--delay:${i*.08}s"><div class="career-date">${x.period}</div><span class="career-node"></span><div class="career-content"><small>${x.company}</small><h2>${x.role}</h2><p>${x.summary}</p><ul>${(x.highlights||[]).map(h=>`<li>${h}</li>`).join('')}</ul></div></article>`).join('');const obs=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle('visible',e.isIntersecting)),{threshold:.18});qa('.career-entry').forEach(e=>obs.observe(e));addEventListener('scroll',()=>{const r=el.getBoundingClientRect(),progress=Math.max(0,Math.min(1,(innerHeight*.58-r.top)/(r.height-innerHeight*.25)));el.style.setProperty('--progress',`${progress*100}%`)},{passive:true})}
async function skills(){const cg=q('#competency-grid'),tg=q('#technology-groups');if(!cg||!tg)return;let d=await fetch(`${BASE}/data/skills.json`).then(r=>r.json());if(LANG==='en-US'&&d.en)d={...d,...d.en};cg.innerHTML=d.competencies.map((x,i)=>`<article class="competency-card"><span>${String(i+1).padStart(2,'0')}</span><h3>${x.name}</h3><p>${x.description}</p></article>`).join('');tg.innerHTML=d.technologyGroups.map(g=>`<section class="technology-group"><p class="eyebrow">${g.name}</p><div class="technology-cards">${g.items.map(i=>`<article>${i}</article>`).join('')}</div></section>`).join('')}
function character(){const video=q('#hero-character');if(!video||video.tagName!=='VIDEO')return;if(matchMedia('(prefers-reduced-motion: reduce)').matches){video.pause();video.currentTime=0;return}video.muted=true;const play=()=>video.play().catch(()=>{});video.addEventListener('canplay',play,{once:true});play()}
function contact(){const f=q('.contact-form');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('[type=submit]'),st=q('.form-status',f),old=b.innerHTML;b.disabled=true;b.textContent=tx('Enviando...','Sending...');try{const r=await fetch(f.action,{method:'POST',body:new FormData(f),headers:{Accept:'application/json'}});if(!r.ok)throw Error();st.textContent=tx('Mensagem enviada com sucesso!','Message sent successfully!');st.className='form-status success';f.reset()}catch{st.textContent=tx('Não foi possível enviar. Use o e-mail direto.','Unable to send. Please use direct email.');st.className='form-status error'}finally{b.disabled=false;b.innerHTML=old}}}
async function translateStatic(){document.documentElement.lang=LANG==='en-US'?'en':'pt-BR';if(LANG!=='en-US')return;try{const d=await fetch(`${BASE}/data/i18n/en-US.json`).then(r=>r.json()),w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const t=n.nodeValue.trim();if(d[t])n.nodeValue=n.nodeValue.replace(t,d[t])}qa('[placeholder]').forEach(e=>{if(d[e.placeholder])e.placeholder=d[e.placeholder]})}catch{}}
loader();chrome();theme();neural();character();contact();translateStatic();featured();catalog();detail();career();skills();
