import fs from 'node:fs';import path from 'node:path';
const root=process.cwd();
const incoming=path.resolve(import.meta.dirname,'content','projects');
const copy=(src,dst)=>{fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(src,dst)};
const walk=(dir)=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);
for(const file of walk(incoming)) copy(file,path.join(root,path.relative(import.meta.dirname,file)));
const catalog=path.join(root,'data','projects.json');const projects=JSON.parse(fs.readFileSync(catalog,'utf8'));
for(const id of ['nexus-ai','ai-enablement-hub']){const p=JSON.parse(fs.readFileSync(path.join(root,'content','projects',id,'project.json'),'utf8'));const i=projects.findIndex(x=>x.id===id);if(i>=0)projects[i]=p;else projects.push(p)}
projects.sort((a,b)=>Number(b.featured)-Number(a.featured)||b.year-a.year);fs.writeFileSync(catalog,JSON.stringify(projects,null,2)+'\n');
const appPath=path.join(root,'app.js');let app=fs.readFileSync(appPath,'utf8');
if(!app.includes('function loader(){')||(!app.includes('function neural(){')&&!app.includes('function neural(seed=null)'))) throw new Error('app.js incompatível: funções loader/neural não encontradas.');
const replacement=`function loader(){
 const el=q('#page-loader');if(!el){neural();return}if(PAGE!=='inicio'){el.remove();neural();return}
 const canvas=q('#loader-network',el),ctx=canvas?.getContext('2d'),media=q('#hero-character'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const started=performance.now(),minTime=reduced?450:2450,maxTime=4400;let resourceReady=!media||media.readyState>=3,done=false,raf=0,w=0,h=0,dpr=1,nodes=[],edges=[],cx=0,cy=0;
 const clamp=v=>Math.max(0,Math.min(1,v)),ease=v=>1-Math.pow(1-v,3);
 const resize=()=>{if(!canvas||!ctx)return;dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;cx=w/2;cy=h/2;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const total=w<600?38:72,maxR=Math.hypot(w,h)*.53;nodes=Array.from({length:total},(_,i)=>{const ring=1+Math.floor(i/9),angle=i*2.399+Math.sin(i)*.18,radius=Math.min(maxR,(ring/(Math.ceil(total/9)+.15))*maxR)*(0.78+((i*37)%21)/100);return{tx:cx+Math.cos(angle)*radius,ty:cy+Math.sin(angle)*radius,born:i/(total*.9),size:2.1+(i%5)*.45,x:cx,y:cy}});edges=[];nodes.forEach((n,i)=>{const prev=nodes.slice(0,i).map((o,j)=>({j,d:Math.hypot(n.tx-o.tx,n.ty-o.ty)})).sort((a,b)=>a.d-b.d).slice(0,i%4===0?3:2);prev.forEach(v=>{if(v.d<Math.max(180,Math.min(w,h)*.34))edges.push([i,v.j])})})};
 const draw=now=>{if(done||!ctx)return;const elapsed=now-started,progress=clamp(elapsed/minTime);ctx.clearRect(0,0,w,h);nodes.forEach(n=>{const local=ease(clamp((progress-n.born)/.24));n.x=cx+(n.tx-cx)*local;n.y=cy+(n.ty-cy)*local});edges.forEach(([ai,bi],idx)=>{const a=nodes[ai],b=nodes[bi],born=Math.max(a.born,b.born);if(progress<born)return;const reveal=ease(clamp((progress-born)/.16));ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(a.x+(b.x-a.x)*reveal,a.y+(b.y-a.y)*reveal);ctx.strokeStyle=\`rgba(73,157,242,\${.08+reveal*.3})\`;ctx.lineWidth=1.15;ctx.stroke();if(progress>.28&&reveal>.8){const t=(elapsed*.00042+idx*.173)%1,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;ctx.beginPath();ctx.arc(x,y,idx%6===0?3.7:2.3,0,Math.PI*2);ctx.fillStyle='rgba(111,190,255,.96)';ctx.shadowColor='rgba(66,158,248,.95)';ctx.shadowBlur=14;ctx.fill();ctx.shadowBlur=0}});nodes.forEach((n,i)=>{if(progress<n.born)return;const local=clamp((progress-n.born)/.16),pulse=1+Math.sin(elapsed*.004+i)*.2;ctx.beginPath();ctx.arc(n.x,n.y,n.size*local*pulse,0,Math.PI*2);ctx.fillStyle='rgba(92,177,255,.88)';ctx.shadowColor='rgba(55,145,235,.9)';ctx.shadowBlur=9;ctx.fill();ctx.shadowBlur=0});raf=requestAnimationFrame(draw)};
 const handoff=()=>{if(done||performance.now()-started<minTime||!resourceReady)return;done=true;cancelAnimationFrame(raf);const old=q('#starfield');if(old&&canvas){old.replaceWith(canvas);canvas.id='starfield';canvas.removeAttribute('style');neural({canvas,nodes:nodes.map(n=>({x:n.x,y:n.y,bx:n.tx,by:n.ty,r:n.size,phase:Math.random()*7})),edgePairs:edges})}el.classList.add('handoff');document.body.classList.add('content-ready');setTimeout(()=>{el.classList.add('complete');document.body.classList.remove('loader-active','home-loading')},720);setTimeout(()=>el.remove(),1550)};
 if(media&&!resourceReady)media.addEventListener('canplay',()=>{resourceReady=true;handoff()},{once:true});if(reduced){handoff()}else{resize();addEventListener('resize',resize,{passive:true});raf=requestAnimationFrame(draw)}setTimeout(handoff,minTime);setTimeout(()=>{resourceReady=true;handoff()},maxTime)
}
function neural(seed=null){
 const c=seed?.canvas||q('#starfield');if(!c)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)return;const ctx=c.getContext('2d');let w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio||1,2),nodes=seed?.nodes||[],edges=[],pulses=[],pointer={x:-999,y:-999},cluster=null,lastBurst=0,nextBurst=650;
 const rand=(a,b)=>a+Math.random()*(b-a);
 function rebuild(preserve=false){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(!preserve||!nodes.length){const total=Math.min(118,Math.max(62,Math.floor(w*h/14500)));nodes=Array.from({length:total},()=>({bx:rand(0,w),by:rand(0,h),x:0,y:0,r:rand(2.2,4.1),phase:rand(0,7)}));nodes.forEach(n=>{n.x=n.bx;n.y=n.by})}edges=[];if(preserve&&seed?.edgePairs){seed.edgePairs.forEach(([ai,bi])=>{if(nodes[ai]&&nodes[bi])edges.push({ai,bi,a:nodes[ai],b:nodes[bi]})})}else nodes.forEach((n,i)=>{const near=nodes.map((o,j)=>({j,d:Math.hypot(o.bx-n.bx,o.by-n.by)})).filter(v=>v.j!==i).sort((a,b)=>a.d-b.d).slice(0,3);near.forEach(v=>{const a=Math.min(i,v.j),b=Math.max(i,v.j);if(v.d<235&&!edges.some(e=>e.ai===a&&e.bi===b))edges.push({ai:a,bi:b,a:nodes[a],b:nodes[b]})})});window.__networkStats={nodes:nodes.length,edges:edges.length,pulses:0}}
 function launch(count=5,origin=null,strong=false){let pool=edges;if(origin)pool=edges.filter(e=>Math.min(Math.hypot(e.a.x-origin.x,e.a.y-origin.y),Math.hypot(e.b.x-origin.x,e.b.y-origin.y))<300);if(!pool.length)pool=edges;for(let i=0;i<count&&pool.length;i++){const edge=pool[Math.floor(Math.random()*pool.length)],reverse=Math.random()>.5;pulses.push({a:reverse?edge.b:edge.a,b:reverse?edge.a:edge.b,t:rand(-.12,.12),speed:rand(strong?.018:.009,strong?.027:.015),strong})}window.__networkStats.pulses=pulses.length}
 addEventListener('resize',()=>rebuild(false),{passive:true});addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY},{passive:true});addEventListener('pointerleave',()=>{pointer.x=pointer.y=-999});addEventListener('pointerdown',e=>{cluster={x:e.clientX,y:e.clientY,start:performance.now(),life:1900};launch(18,{x:e.clientX,y:e.clientY},true)});
 function draw(now){ctx.clearRect(0,0,w,h);const rgb=getComputedStyle(document.documentElement).getPropertyValue('--star').trim()||'36,116,210';let phase=0;if(cluster){phase=Math.min(1,(now-cluster.start)/cluster.life);if(phase>=1)cluster=null}nodes.forEach(n=>{let tx=n.bx+Math.sin(now*.00018+n.phase)*5,ty=n.by+Math.cos(now*.00015+n.phase)*5;if(cluster){const d=Math.hypot(n.bx-cluster.x,n.by-cluster.y);if(d<270){const pull=Math.sin(phase*Math.PI)*.66,ang=Math.atan2(n.by-cluster.y,n.bx-cluster.x),radius=42+d*.24;tx=tx*(1-pull)+(cluster.x+Math.cos(ang)*radius)*pull;ty=ty*(1-pull)+(cluster.y+Math.sin(ang)*radius)*pull}}n.x+=(tx-n.x)*.1;n.y+=(ty-n.y)*.1});edges.forEach(e=>{const mx=(e.a.x+e.b.x)/2,my=(e.a.y+e.b.y)/2,near=Math.hypot(mx-pointer.x,my-pointer.y)<210;ctx.beginPath();ctx.moveTo(e.a.x,e.a.y);ctx.lineTo(e.b.x,e.b.y);ctx.lineWidth=near?1.75:1.15;ctx.strokeStyle=\`rgba(\${rgb},\${near?.34:.17})\`;ctx.stroke()});nodes.forEach(n=>{const near=Math.hypot(n.x-pointer.x,n.y-pointer.y)<190;ctx.beginPath();ctx.arc(n.x,n.y,n.r+(near?.7:0),0,Math.PI*2);ctx.fillStyle=\`rgba(\${rgb},\${near?.92:.62})\`;ctx.shadowColor=\`rgba(\${rgb},.72)\`;ctx.shadowBlur=near?12:5;ctx.fill();ctx.shadowBlur=0});if(now-lastBurst>nextBurst){launch(Math.floor(rand(4,8)));lastBurst=now;nextBurst=rand(620,1150)}pulses=pulses.filter(o=>{const mx=(o.a.x+o.b.x)/2,my=(o.a.y+o.b.y)/2,boost=Math.hypot(mx-pointer.x,my-pointer.y)<220?2.6:1;o.t+=o.speed*boost;const t=Math.max(0,o.t),tail=Math.max(0,t-(o.strong?.2:.12)),x1=o.a.x+(o.b.x-o.a.x)*tail,y1=o.a.y+(o.b.y-o.a.y)*tail,x2=o.a.x+(o.b.x-o.a.x)*t,y2=o.a.y+(o.b.y-o.a.y)*t;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.lineWidth=o.strong?3.5:2.4;ctx.strokeStyle=\`rgba(\${rgb},\${o.strong?.96:.82})\`;ctx.shadowColor=\`rgba(\${rgb},1)\`;ctx.shadowBlur=o.strong?18:13;ctx.stroke();ctx.beginPath();ctx.arc(x2,y2,o.strong?4.6:3.4,0,Math.PI*2);ctx.fillStyle=\`rgba(\${rgb},1)\`;ctx.fill();ctx.shadowBlur=0;return o.t<1.02});window.__networkStats.pulses=pulses.length;requestAnimationFrame(draw)}
 rebuild(!!seed);launch(7);requestAnimationFrame(draw)
}
`;
app=app.replace(/function loader\(\)\{[\s\S]*?(?=async function projects\(\))/,replacement);
app=app.replace('loader();chrome();theme();neural();character();','loader();chrome();theme();character();');
app=app.replace(/const demo=p\.demo\?\.mode==='github-html'\?[\s\S]*?:'';/,`const demoSrc=p.demo?.mode==='github-html'?\`\${BASE}/\${p.demo.embedPath}\`:(p.demo?.embedUrl||'');const demo=demoSrc?\`<section class="section"><div class="section-head"><div><span class="eyebrow">\${tx('DEMONSTRAÇÃO','DEMO')}</span><h2>\${tx('Explore a solução.','Explore the solution.')}</h2></div></div><div class="demo-frame"><iframe src="\${demoSrc}" title="\${p.title}" loading="lazy" allowfullscreen></iframe></div>\${p.demo?.externalUrl?\`<p><a class="secondary" href="\${p.demo.externalUrl}" target="_blank" rel="noopener">\${tx('Abrir relatório em nova aba','Open report in a new tab')} →</a></p>\`:''}</section>\`:'';`);
fs.writeFileSync(appPath,app);
console.log('Atualização aplicada: projetos copiados, catálogo atualizado e rede neural unificada.');
